theme: jekyll-theme-slate
name: : FOCUS IMPORT AND EXPORT ISSUES WITH R PROJECT  
decription: by gpj18-r_coders

************************
                                                      This group members are
                         #### Mercan KARACABEY, Leyla YİĞİT, Merve ÖZEN ŞAHİN, Mehmet AK, Büşra AYDEMİR



gpj18-r_coders created by GitHub Classroom



