<<<<<<< HEAD

theme: jekyll-theme-merlot
title: r_coders
description:FOCUS IMPORT AND EXPORT ISSUES WITH R PROJECT
favicon: "https://github.com/MEF-BDA503/gpj18-r_coders/blob/master/img/R_developers.jpg"O
=======

theme: jekyll-theme-slate
title: r_coders
description: FOCUS IMPORT AND EXPORT ISSUES WITH R PROJECT
# favicon: "https://github.com/MEF-BDA503/gpj18-r_coders/blob/master/img/R_developers.jpg"
>>>>>>> 4b69b63e68738e6128bc1bad6a37f324c7654b0b
