theme: jekyll-theme-slate
title: r_coders
description:FOCUS IMPORT AND EXPORT ISSUES WITH R PROJECT

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/Dev.png"