---
title: "References"
date: "23.12.2018"
output: html_document
---
#### Group Name :<span style="color:red"> R_Coders</span>
#### Project Name : Import - Export Analysis 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
``` 

library(tidyverse)
library(dplyr)
library(readxl)
library(dplyr )
library(tidyverse )
library(lubridate )
#EXCEL DATA SOURCES 

*IMPORT DATA SOURCES:
[IMPORT DATA SOURCES]( http://www.oaib.gov.tr/tr/default.html)

*EXPORT DATA SOURCES:
[EXPORT DATA SOURCES](http://www.tim.org.tr/tr/ihracat-rakamlari.html)

*INFLATION:
[INFLATION](https://www.tcmb.gov.tr/wps/wcm/connect/TR/TCMB+TR/Main+Menu/Istatistikler/Enflasyon+Verileri/Tuketici+Fiyatlari)

*EXCHANGE RATE:
[INFLATION](https://github.com/algopoly/EVDS)

*INTEREST RATE
[INTEREST RATE](https://evds2.tcmb.gov.tr/)


***************************************************************************************************************************************************************************************


#r SOURCE LINKS FOR HELP

#stackoverflow.com is used for How do I add a URL to R markdown? and many questions
[stackoverflow.com](https://stackoverflow.com/questions/29787850/how-do-i-add-a-url-to-r-markdown)

#This page is used for Process Journal Development :
[Process Journal Development](https://github.com/jtleek/modules/blob/master/05_ReproducibleResearch/Markdown/index.md)

#This page is used for GGPLOT
[GGPLOT](http://kbroman.org/datacarpentry_R_2017-01-10/03-ggplot2.html)

#This page is used for INDEX.Md creation and theme adjustments
[ INDEX.Md creation and theme adjustments](https://bookdown.org/yihui/rmarkdown/beamer-presentation.html#themes)

#This page is used for waffle chart and pir chart 
[chart](http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html#Pie%20Chart)

#This page is used for Summarise and mutate multiple columns
[Summarise and mutate multiple columns](https://dplyr.tidyverse.org/reference/summarise_all.html)

#This page is used for Shiny Dashboard Example
[Shiny](https://bookdown.org/yihui/rmarkdown/shiny.html)

#This pages is used for add picture to index.mdb
[index.mdb coding](https://github.com/d0ugal/mkdocs/commit/d9e50170a417601bfd4f804bf6b142c696aeaa9f)
[index.mdb coding2](https://www.mkdocs.org/user-guide/writing-your-docs/#linking-to-images-and-media)

#Learn Shiny
[Learn Shiny](https://www.youtube.com/watch?v=Gyrfsrd4zK0)


***************************************************************************************************************************************************************************************


#BUSINESS ANALYSIS SOURCES

#Foreign Trade Deficit is the deficit of between export and import
[Foreign Trade Deficit](http://www.paraanaliz.com/2017/ekonomi/ithalattaki-sicrama-dis-ticarette-makasi-acti-15739/)

#Inflation,currency,import,export,ralationship
[Imports is affected from inflation and currency](https://tradingeconomics.com/turkey/imports)

#Import,export perspective of products heatmaps, time trend
[Import,export perspective](https://atlas.media.mit.edu/en/profile/country/tur/)

#Export, Import Product Range 
[Export, Import Product Range Shiny Development]("https://shiny.rstudio.com")


***************************************************************************************************************************************************************************************

#Tols used for Project
[Diagram Development](https://www.lucidchart.com/documents/edit/f855c477-fe36-4880-bd0e-35c7a1a2333c/0)




