---
title: "Proje"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(ggplot2)
library(shiny)
library(tidyverse)
library(ggplot2movies)
```



```{r cars}
#Download Raw Data
# Create a temporary file
tmp<-tempfile(fileext=".xlsx")
# Download file from repository to the temp file
download.file("https://github.com/MEF-BDA503/gpj18-r_coders/blob/master/import_data/US_Dollar_Montly_Rate.xlsx?raw=true",mode="wb",destfile=tmp)
# Read that excel file using readxl package's read_excel function. You might need to adjust the parameters (skip, col_names) according to your raw file's format.
raw_data<-readxl::read_excel(tmp,skip=7,col_names=FALSE)
# Remove the temp file
file.remove(tmp)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
raw_data <- raw_data %>%
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r MAKE CIVILIZED DATA}
#In order to make the data standardized and workable we need to define column names and remove NA values for this example. 
#Please use the same column names in your examples also.
# Use the same column names in your data.
colnames(raw_data) <- c("Date","Dollar")
# Now we replace NA values with 0 and label the time period with year and month, so when we merge the data we won't be confused.
US_Dollar_Montly_Rate<- raw_data 

print(US_Dollar_Montly_Rate,width=Inf)
```





```{r pressure, echo=FALSE}
saveRDS(US_Dollar_Montly_Rate, file = "US_Dollar_Montly_Rate")
```

